data:
  raw_path: "data/raw/Dataset.csv"
  processed_path: "data/processed/cleaned_data.csv"
  train_path: "data/processed/train.csv"
  test_path: "data/processed/test.csv"
    # Nouveaux chemins à ajouter
  augmented_path: "data/augmented/augmented_{date}.csv"
  vectorizer_path: "artifacts/vectorizers/tfidf_vectorizer.pkl"

processing:
  batch_size: 512  # Taille des lots pour le streaming
  max_workers: 4   # Nombre de threads pour le parallélisme
  text:
    min_token_length: 2
    remove_stopwords: true

mlflow:
  tracking_uri: "http://localhost:5000"
  experiment_name: "SentimentAnalysis"