# configs/schema.yaml - Version corrigée
text_column: "text"       # Doit correspondre au nom de colonne dans vos données
target_column: "label"    # Doit correspondre au nom de colonne dans vos données