mlflow:
  tracking_uri: "http://localhost:5000"
  experiment_name: "text-classification"
  run_name: "experiment"

models:
  sgd:
    penalty: "l2"
    alpha: 0.0001
    max_iter: 1000
    
  logistic_regression:
    penalty: "l2"
    C: 1.0
    max_iter: 1000
    solver: "lbfgs"
    
  svm:
    kernel: "rbf"
    C: 1.0
    gamma: "scale"

paths:
  data_dir: "data/"
  models_dir: "models/"

text_processing:
  framework:
    active: "sklearn"

data_version: "1.0" 

hhh