name: Security Checks
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Étape optionnelle si vous n'avez pas GITLEAKS_LICENSE
      - name: Detect secrets with Gitleaks (basic)
        if: false  # Désactivé par défaut
        uses: gitleaks/gitleaks-action@v2
        with:
          redact: true
          exit-code: 0  # Ne pas bloquer le workflow

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'table'  # Format simple pour les logs
          exit-code: '1'
          severity: 'CRITICAL,HIGH'
          ignore-unfixed: true

      - name: Scan Dockerfile
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          scan-ref: 'Dockerfile'
          format: 'table'
          exit-code: '1'